# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.7.2.
FROM ghcr.io/visualon/buildpack:latest@sha256:b8e53042c6fecc76b690832f3af6ce1af96a411e960fc3519f1f7c4dbc407792

LABEL `
  org.opencontainers.image.source="https://github.com/visualon/docker-builder" `
  org.opencontainers.image.url="https://github.com/visualon/docker-builder"

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool pwsh 7.1.3

# renovate: datasource=github-releases lookupName=nodejs/node versioning=node
RUN install-tool node 14.16.1

# renovate: datasource=npm
RUN install-npm yarn 1.22.10

# install last to get latest vs updates
RUN install-tool vs-tools
