# escape=`

# Use the latest buildpack.
FROM ghcr.io/visualon/buildpack:2.0.47@sha256:af44d415c392de69ac7b6c71986d5246144c5a465ad5046b52b08fb01e93c91d

LABEL `
  org.opencontainers.image.source="https://github.com/visualon/docker-builder" `
  org.opencontainers.image.url="https://github.com/visualon/docker-builder"

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool powershell v7.2.3

# renovate: datasource=github-releases lookupName=nodejs/node versioning=node
RUN install-tool node 16.15.0

# renovate: datasource=npm
RUN install-npm yarn 1.22.18

# renovate: datasource=adoptium-java lookupName=java-jre
RUN install-tool java 11.0.15+10

# install last to get latest vs updates
RUN install-tool vs-tools
