# escape=`

# Use the latest buildpack.
FROM ghcr.io/visualon/buildpack:2.0.45@sha256:4889fe83e05c506eb5693146420ee9fa3ab4b94191d034e6855d60291bddb841

LABEL `
  org.opencontainers.image.source="https://github.com/visualon/docker-builder" `
  org.opencontainers.image.url="https://github.com/visualon/docker-builder"

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool powershell v7.2.2

# renovate: datasource=github-releases lookupName=nodejs/node versioning=node
RUN install-tool node 14.19.1

# renovate: datasource=npm
RUN install-npm yarn 1.22.18

# renovate: datasource=adoptium-java lookupName=java-jre
RUN install-tool java 11.0.14+9

# install last to get latest vs updates
RUN install-tool vs-tools
