# escape=`

# Use the latest buildpack.
FROM ghcr.io/visualon/buildpack:latest@sha256:8974c685a20d6bda40bce87edcfaac4c142094118baba86609d840f6f30bf903

LABEL `
  org.opencontainers.image.source="https://github.com/visualon/docker-builder" `
  org.opencontainers.image.url="https://github.com/visualon/docker-builder"

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool pwsh v7.1.4

# renovate: datasource=github-releases lookupName=nodejs/node versioning=node
RUN install-tool node 14.18.0

# renovate: datasource=npm
RUN install-npm yarn 1.22.15

# renovate: datasource=adoptium-java lookupName=java-jre
RUN install-tool java 11.0.12+7

# install last to get latest vs updates
RUN install-tool vs-tools
