# escape=`

# Use the latest buildpack.
FROM ghcr.io/visualon/buildpack:latest@sha256:e4e8134be9ad32e8aa61ddd896f1cc716a5f15dfa44b068ca7e38b27855f65ff

LABEL `
  org.opencontainers.image.source="https://github.com/visualon/docker-builder" `
  org.opencontainers.image.url="https://github.com/visualon/docker-builder"

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool pwsh v7.1.4

# renovate: datasource=github-releases lookupName=nodejs/node versioning=node
RUN install-tool node 14.17.6

# renovate: datasource=npm
RUN install-npm yarn 1.22.11

# install last to get latest vs updates
RUN install-tool vs-tools
